plugins {
  id 'java-gradle-plugin'
  id 'maven-publish'
  id 'idea'
  id "com.gradle.plugin-publish" version "2.1.1"
}

group = 'com.katalon.gradle.plugin'
version = '0.2.0'

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

publishing {
  repositories {
    maven {
      url = "../consuming/maven-repo"
    }
  }
}

gradlePlugin {
  website = 'https://www.katalon.com/'
  vcsUrl = 'https://github.com/katalon-studio/gradle-plugin'

  plugins {
    katalon {
      id = 'com.katalon.gradle-plugin'
      displayName = 'Katalon Gradle Plugin'
      description = 'Katalon Gradle Plugin'
      tags.set(['katalon'])
      implementationClass = 'com.katalon.gradle.plugin.KatalonGradlePlugin'
    }
  }
}

repositories {
  mavenCentral()
  maven { url = 'https://plugins.gradle.org/m2/' }
}

dependencies {
  implementation 'com.gradleup.shadow:shadow-gradle-plugin:9.6.1'
}
