name: Gradle Build and Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
#     environment: gradle-publish
    steps:
      - uses: actions/checkout@v2
#       For specific gradle version
#       - uses: gradle/gradle-build-action@v2
#         with:
#           gradle-version: 7.3.3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build and Publish
        run: |
          gradle clean build
          gradle publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_USR }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_PSW }}
